export const DEFAULT_ACTION = "DEFAULT_ACTION";

export const SET_USER = "SET_USER";
export const SET_LOCATION = "SET_LOCATION";
export const UNSET_USER = "UNSET_USER";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const SET_SPS = "SET_SPS";
export const SPS_LOADING = "SPS_LOADING";
export const ERROR_SPS = "ERROR_SPS";

export const SET_SERVICES = "SET_SERVICES";
export const SERVICES_LOADING = "SERVICES_LOADING";
export const ERROR_SERVICES = "ERROR_SERVICES";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const ERROR_STORE = "ERROR_STORE";

export const SET_GENDER_FILTER = "SET_GENDER_FILTER";
export const SET_SERVICE_FILTER = "SET_SERVICE_FILTER";
// export const REMOVE_PRODUCT = "REMOVE_PRODUCT"

export const GET_COMMANDS = "GET_COMMANDS";
export const ERROR_GET_COMMANDS = "ERROR_GET_COMMANDS";
export const GET_COMMANDS_LOADING = "GET_COMMANDS_LOADING";

export const GET_INTERVENTIONS = "GET_INTERVENTIONS";
export const ERROR_GET_INTERVENTIONS = "ERROR_GET_INTERVENTIONS";
export const GET_INTERVENTIONS_LOADING = "GET_INTERVENTIONS_LOADING";

export const SET_COMMAND = "SET_COMMAND";
export const CANCEL_COMMAND = "CANCEL_COMMAND";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const REMOVE_QUANTITY = "REMOVE_QUANTITY";

export const SET_CURRENT = "SET_CURRENT";
export const LOADING_CURRENT_INTERVENTION = "LOADING_CURRENT_INTERVENTION";
export const SET_CURRENT_INTERVENTION = "SET_CURRENT_INTERVENTION";
export const SET_CURRENT_SP = "SET_CURRENT_SP";
export const UNSET_CURRENT = "UNSET_CURRENT";

export const SET_PRODUCT = "SET_PRODUCT";
export const ERROR_CART = "ERROR_CART";
export const CART_LOADING = "CART_LOADING";
