export const DEFAULT_ACTION = "DEFAULT_ACTION";

export const USER_LOADING = "USER_LOADING";
export const SET_USER = "SET_USER";
export const SET_USER_STATE = "SET_USER_STATE";
export const SET_LOCATION = "SET_LOCATION";
export const UNSET_USER = "UNSET_USER";
export const ERROR_USER = "ERROR_USER";

export const SET_SERVICES = "SET_SERVICES";
export const SERVICES_LOADING = "SERVICES_LOADING";
export const ERROR_SERVICES = "ERROR_SERVICES";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const STORE_LOADING_PRODUCTS = "STORE_LOADING_PRODUCTS";
export const STORE_LOADING_CATEGORIES = "STORE_LOADING_CATEGORIES";
export const ERROR_STORE = "ERROR_STORE";

export const GET_COMMANDS = "GET_COMMANDS"
export const ERROR_GET_COMMANDS = "ERROR_GET_COMMANDS"
export const GET_COMMANDS_LOADING = "GET_COMMANDS_LOADING";

export const GET_INTERVENTIONS = "GET_INTERVENTIONS"
export const ERROR_GET_INTERVENTIONS = "ERROR_GET_INTERVENTIONS"
export const GET_INTERVENTIONS_LOADING = "GET_INTERVENTIONS_LOADING";

export const SET_COMMAND = "SET_COMMAND";
export const CANCEL_COMMAND = "CANCEL_COMMAND";
export const SET_PRODUCT = "SET_PRODUCT";
export const ERROR_CART = "ERROR_CART"
export const CART_LOADING = "CART_LOADING"
